FROM ubuntu:18.04
WORKDIR /app
COPY package.json /app
RUN npm install 
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get install -y nodejs
COPY . /app
CMD ["npm", "start"] 